# This is a Headless Service, which is used to control the domain of the Pods in the StatefulSet.
apiVersion: v1
kind: Service
metadata:
  name: postgres_sql  # Name of the service.
  labels:
    app: postgres  # Label to identify this service.
spec:
  ports:
  - port: 5432  # The port that the service exposes.
  clusterIP: None  # This makes the service a headless service.
  selector:
    app: postgres  # This service will route traffic to Pods with the label `app: postgres`.

---
# This StatefulSet represents a group of Pods with stable storage and network identities.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres  # Name of the StatefulSet.
spec:
  serviceName: postgres_sql  # The name of the headless service this StatefulSet is governed by.
  replicas: 3  # Number of Pods to run.
  selector:
    matchLabels:
      app: postgres  # Label selector for Pods in the StatefulSet.
  template:  # Pod template.
    metadata:
      labels:
        app: postgres  # Labels for Pods in the StatefulSet.
    spec:  # Pod specification.
      containers:
      - name: postgres  # Name of the main container.
        image: postgres:latest  # Image to use for the container.
        env:  # Environment variables for the container.
        - name: POSTGRES_USER  # The username for the PostgreSQL instance.
          valueFrom:
            secretKeyRef:  # Get the username from a Secret.
              name: postgres-credentials  # Name of the Secret.
              key: username  # Key to look up in the Secret.
        - name: POSTGRES_PASSWORD  # The password for the PostgreSQL instance.
          valueFrom:
            secretKeyRef:  # Get the password from a Secret.
              name: postgres-credentials  # Name of the Secret.
              key: password  # Key to look up in the Secret.
        ports:
        - containerPort: 5432  # The port that the PostgreSQL server listens on.
          name: postgres
        volumeMounts:  # Storage volumes to mount.
        - name: postgres-data  # Name of the volume.
          mountPath: /var/lib/postgresql/data  # Path in the container where the volume is mounted.
  volumeClaimTemplates:  # A template for creating PersistentVolumeClaims.
  - metadata:
      name: postgres-data  # Name of the PersistentVolumeClaim.
    spec:
      accessModes: [ "ReadWriteOnce" ]  # Access modes for the volume.
      resources:
        requests:
          storage: 1Gi  # Size of the storage.
