apiVersion: v1
kind: Service
metadata:
  name: postgres-sql
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-sql
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
          
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc


apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-job
  template:
    metadata:
      labels:
        app: data-job
    spec:
      containers:
      - name: data-job
        image: pipeline_make
        env:
        - name: WAREHOUSE_USER
          value: ${POSTGRES_USER}
        - name: WAREHOUSE_PASSWORD
          value: ${POSTGRES_PASSWORD}
        - name: WAREHOUSE_DB
          value: ${POSTGRES_DB}
        - name: WAREHOUSE_HOST
          value: warehouse
        - name: WARREHOUSE_PORT
          value: ${POSTGRES_PORT}
        - name: CONTAINER_NAME
          value: ${CONTAINER_NAME}
        volumeMounts:
        - name: code
          mountPath: /code