name: conti_deliv

on: 
  pull_request:
    branches: ["main"]

  push:
    branches: ["dev"]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      # checks out a copy of repo on the ubuntu runner
      - uses: actions/checkout@v2

      # spin up containers from the compose file
      - name: containers up
        run: make up
        
      # run various tests in the container
      - name: test ci 
        run: make start_integration


